#!/usr/bin/perl

use List::Util qw(shuffle);

sub pickcardsfromfilename {
	$filename = shift;
	#print("$filename\n");
	open(FILE, $filename) or die $!;
	@cards = <FILE>;
	close FILE;
	
	
	for ($i = 0; $i < scalar(@cards); $i++) {
	
		#unshift(@a, $i) if $cards[$i] =~ m(\/\/);  # double forward slash
		if($cards[$i] =~ m(\/\/)) {
			unshift(@a, $i);
#			print("$cards[$i]\n");
		}
		if($cards[$i] !~ m/\w/) {
			unshift(@a, $i);
#			print("$cards[$i]\n");  # Any card should have a word in it
		}
	}

	foreach $r (@a) {
		delete $cards[$r];
	}
	
	print(OUT "@cards[(shuffle(0..$#cards))[1..$numcards]]");
}

# Autogen file name

$mytime = time();

$file = "deck_" . $mytime . ".mwDeck";

open OUT, ">", $file or die $!;

# First, header.

print(OUT "// Autogenerated deck file composed the autogenbigdeck.pl\n");
print(OUT "// NAME: Autogenerated Deck at $mytime\n");

# print basic lands
# TODO:  Make basic land files too, and pull eight random cards from there.
#        So you get different pictures, of course!
print(OUT "    8 [LRW] Forest (1)\n");
print(OUT "    8 [LRW] Swamp (1)\n");
print(OUT "    8 [LRW] Plains (1)\n");
print(OUT "    8 [LRW] Mountain (1)\n");
print(OUT "    8 [LRW] Island (1)\n");

# print crosslands, because getting them at random sucks
print(OUT "    1 [R] Badlands\n");
print(OUT "    1 [R] Bayou\n");
print(OUT "    1 [R] Plateau\n");
print(OUT "    1 [R] Savannah\n");
print(OUT "    1 [R] Scrubland\n");
print(OUT "    1 [R] Taiga\n");
print(OUT "    1 [R] Tropical Island\n");
print(OUT "    1 [R] Tundra\n");
print(OUT "    1 [R] Underground Sea\n");
print(OUT "    1 [R] Volcanic Island\n");

# Due to making the code simpler, I will simply separate lands/colors/gold/artifacts
# into individual files, and then simply select 20 of each one.

# Except we'll use more lands.

$numcards = 50;  # This plus 7 or 8 of each basic land seems a good amount.

# I am actually going to cheat, and just call the sub with land three times

pickcardsfromfilename("lands.mwDeck");

$numcards = 20;
pickcardsfromfilename("artifacts.mwDeck");
pickcardsfromfilename("black.mwDeck");
pickcardsfromfilename("blue.mwDeck");
pickcardsfromfilename("gold.mwDeck");
pickcardsfromfilename("green.mwDeck");
pickcardsfromfilename("red.mwDeck");
pickcardsfromfilename("white.mwDeck");